CREATE TABLE IF NOT EXISTS users
	(
		`id`          INTEGER PRIMARY KEY AUTO_INCREMENT,
		`email`       VARCHAR(255) NOT NULL,
		`first_name`  VARCHAR(255) NOT NULL,
		`last_name`   VARCHAR(255) NOT NULL,
		`password`    VARCHAR(255) NOT NULL,
		`is_active`   BOOLEAN DEFAULT true,
		`created_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		`updated_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)
	